type Municipio = {
	value: string;
	label: string;
};

export const municipalityByDepartment: Record<string, Municipio[]> = {
	Ahuachapán: [
		{ value: "Ahuachapán", label: "Ahuachapán" },
		{ value: "Apaneca", label: "Apaneca" },
		{ value: "Atiquizaya", label: "Atiquizaya" },
		{ value: "Concepción de Ataco", label: "Concepción de Ataco" },
		{ value: "El Refugio", label: "El Refugio" },
		{ value: "Guaymango", label: "Guaymango" },
		{ value: "Jujutla", label: "Jujutla" },
		{ value: "San Francisco Menéndez", label: "San Francisco Menéndez" },
		{ value: "San Lorenzo", label: "San Lorenzo" },
		{ value: "San Pedro Puxtla", label: "San Pedro Puxtla" },
		{ value: "Tacuba", label: "Tacuba" },
		{ value: "Turín", label: "Turín" },
	],
	"Santa Ana": [
		{
			value: "Candelaria de la Frontera",
			label: "Candelaria de la Frontera",
		},
		{ value: "Chalchuapa", label: "Chalchuapa" },
		{ value: "Coatepeque", label: "Coatepeque" },
		{ value: "El Congo", label: "El Congo" },
		{ value: "El Porvenir", label: "El Porvenir" },
		{ value: "Masahuat", label: "Masahuat" },
		{ value: "Metapán", label: "Metapán" },
		{ value: "San Antonio Pajonal", label: "San Antonio Pajonal" },
		{
			value: "San Sebastián Salitrillo",
			label: "San Sebastián Salitrillo",
		},
		{ value: "Santa Ana", label: "Santa Ana" },
		{ value: "Santa Rosa Guachipilín", label: "Santa Rosa Guachipilín" },
		{ value: "Santiago de la Frontera", label: "Santiago de la Frontera" },
		{ value: "Texistepeque", label: "Texistepeque" },
	],
	Sonsonate: [
		{ value: "Acajutla", label: "Acajutla" },
		{ value: "Armenia", label: "Armenia" },
		{ value: "Caluco", label: "Caluco" },
		{ value: "Cuisnahuat", label: "Cuisnahuat" },
		{ value: "Izalco", label: "Izalco" },
		{ value: "Juayúa", label: "Juayúa" },
		{ value: "Nahuizalco", label: "Nahuizalco" },
		{ value: "Nahulingo", label: "Nahulingo" },
		{ value: "Salcoatitán", label: "Salcoatitán" },
		{ value: "San Antonio del Monte", label: "San Antonio del Monte" },
		{ value: "San Julián", label: "San Julián" },
		{ value: "Santa Catarina Masahuat", label: "Santa Catarina Masahuat" },
		{ value: "Santa Isabel Ishuatán", label: "Santa Isabel Ishuatán" },
		{ value: "Santo Domingo Guzmán", label: "Santo Domingo Guzmán" },
		{ value: "Sonsonate", label: "Sonsonate" },
		{ value: "Sonzacate", label: "Sonzacate" },
	],
	Chalatenango: [
		{ value: "Agua Caliente", label: "Agua Caliente" },
		{ value: "Arcatao", label: "Arcatao" },
		{ value: "Azacualpa", label: "Azacualpa" },
		{ value: "Chalatenango", label: "Chalatenango" },
		{ value: "Comalapa", label: "Comalapa" },
		{ value: "Citalá", label: "Citalá" },
		{
			value: "Concepción Quezaltepeque",
			label: "Concepción Quezaltepeque",
		},
		{ value: "Dulce Nombre de María", label: "Dulce Nombre de María" },
		{ value: "El Carrizal", label: "El Carrizal" },
		{ value: "El Paraíso", label: "El Paraíso" },
		{ value: "La Laguna", label: "La Laguna" },
		{ value: "La Palma", label: "La Palma" },
		{ value: "La Reina", label: "La Reina" },
		{ value: "Las Vueltas", label: "Las Vueltas" },
		{ value: "Nueva Concepción", label: "Nueva Concepción" },
		{ value: "Nueva Trinidad", label: "Nueva Trinidad" },
		{ value: "Nombre de Jesús", label: "Nombre de Jesús" },
		{ value: "Ojos de Agua", label: "Ojos de Agua" },
		{ value: "Potonico", label: "Potonico" },
		{ value: "San Antonio de la Cruz", label: "San Antonio de la Cruz" },
		{ value: "San Antonio Los Ranchos", label: "San Antonio Los Ranchos" },
		{ value: "San Fernando", label: "San Fernando" },
		{ value: "San Francisco Lempa", label: "San Francisco Lempa" },
		{ value: "San Francisco Morazán", label: "San Francisco Morazán" },
		{ value: "San Ignacio", label: "San Ignacio" },
		{ value: "San Isidro Labrador", label: "San Isidro Labrador" },
		{ value: "San José Cancasque", label: "San José Cancasque" },
		{ value: "San José Las Flores", label: "San José Las Flores" },
		{ value: "San Luis del Carmen", label: "San Luis del Carmen" },
		{ value: "San Miguel de Mercedes", label: "San Miguel de Mercedes" },
		{ value: "San Rafael", label: "San Rafael" },
		{ value: "Santa Rita", label: "Santa Rita" },
		{ value: "Tejutla", label: "Tejutla" },
	],
	Cuscatlán: [
		{ value: "Candelaria", label: "Candelaria" },
		{ value: "Cojutepeque", label: "Cojutepeque" },
		{ value: "El Carmen", label: "El Carmen" },
		{ value: "El Rosario", label: "El Rosario" },
		{ value: "Monte San Juan", label: "Monte San Juan" },
		{ value: "Oratorio de Concepción", label: "Oratorio de Concepción" },
		{ value: "San Bartolomé Perulapía", label: "San Bartolomé Perulapía" },
		{ value: "San Cristóbal", label: "San Cristóbal" },
		{ value: "San José Guayabal", label: "San José Guayabal" },
		{ value: "San Pedro Perulapán", label: "San Pedro Perulapán" },
		{ value: "San Rafael Cedros", label: "San Rafael Cedros" },
		{ value: "San Ramón", label: "San Ramón" },
		{ value: "Santa Cruz Analquito", label: "Santa Cruz Analquito" },
		{ value: "Santa Cruz Michapa", label: "Santa Cruz Michapa" },
		{ value: "Suchitoto", label: "Suchitoto" },
		{ value: "Tenancingo", label: "Tenancingo" },
	],
	"San Salvador": [
		{ value: "Aguilares", label: "Aguilares" },
		{ value: "Apopa", label: "Apopa" },
		{ value: "Ayutuxtepeque", label: "Ayutuxtepeque" },
		{ value: "Cuscatancingo", label: "Cuscatancingo" },
		{ value: "Ciudad Delgado", label: "Ciudad Delgado" },
		{ value: "El Paisnal", label: "El Paisnal" },
		{ value: "Guazapa", label: "Guazapa" },
		{ value: "Ilopango", label: "Ilopango" },
		{ value: "Mejicanos", label: "Mejicanos" },
		{ value: "Nejapa", label: "Nejapa" },
		{ value: "Panchimalco", label: "Panchimalco" },
		{ value: "Rosario de Mora", label: "Rosario de Mora" },
		{ value: "San Marcos", label: "San Marcos" },
		{ value: "San Martín", label: "San Martín" },
		{ value: "San Salvador", label: "San Salvador" },
		{ value: "Santiago Texacuangos", label: "Santiago Texacuangos" },
		{ value: "Santo Tomás", label: "Santo Tomás" },
		{ value: "Soyapango", label: "Soyapango" },
		{ value: "Tonacatepeque", label: "Tonacatepeque" },
	],
	"La Libertad": [
		{ value: "Antiguo Cuscatlán", label: "Antiguo Cuscatlán" },
		{ value: "Chiltiupán", label: "Chiltiupán" },
		{ value: "Ciudad Arce", label: "Ciudad Arce" },
		{ value: "Colón", label: "Colón" },
		{ value: "Comasagua", label: "Comasagua" },
		{ value: "Huizúcar", label: "Huizúcar" },
		{ value: "Jayaque", label: "Jayaque" },
		{ value: "Jicalapa", label: "Jicalapa" },
		{ value: "La Libertad", label: "La Libertad" },
		{ value: "Santa Tecla", label: "Santa Tecla" },
		{ value: "Nuevo Cuscatlán", label: "Nuevo Cuscatlán" },
		{ value: "San Juan Opico", label: "San Juan Opico" },
		{ value: "Quezaltepeque", label: "Quezaltepeque" },
		{ value: "Sacacoyo", label: "Sacacoyo" },
		{ value: "San José Villanueva", label: "San José Villanueva" },
		{ value: "San Matías", label: "San Matías" },
		{ value: "San Pablo Tacachico", label: "San Pablo Tacachico" },
		{ value: "Talnique", label: "Talnique" },
		{ value: "Tamanique", label: "Tamanique" },
		{ value: "Teotepeque", label: "Teotepeque" },
		{ value: "Tepecoyo", label: "Tepecoyo" },
		{ value: "Zaragoza", label: "Zaragoza" },
	],
	"San Vicente": [
		{ value: "Apastepeque", label: "Apastepeque" },
		{ value: "Guadalupe", label: "Guadalupe" },
		{ value: "San Cayetano Istepeque", label: "San Cayetano Istepeque" },
		{ value: "San Esteban Catarina", label: "San Esteban Catarina" },
		{ value: "San Ildefonso", label: "San Ildefonso" },
		{ value: "San Lorenzo", label: "San Lorenzo" },
		{ value: "San Sebastián", label: "San Sebastián" },
		{ value: "San Vicente", label: "San Vicente" },
		{ value: "Santa Clara", label: "Santa Clara" },
		{ value: "Santo Domingo", label: "Santo Domingo" },
		{ value: "Tecoluca", label: "Tecoluca" },
		{ value: "Tepetitán", label: "Tepetitán" },
		{ value: "Verapaz", label: "Verapaz" },
	],
	Cabañas: [
		{ value: "Cinquera", label: "Cinquera" },
		{ value: "Dolores", label: "Dolores" },
		{ value: "Guacotecti", label: "Guacotecti" },
		{ value: "Ilobasco", label: "Ilobasco" },
		{ value: "Jutiapa", label: "Jutiapa" },
		{ value: "San Isidro", label: "San Isidro" },
		{ value: "Sensuntepeque", label: "Sensuntepeque" },
		{ value: "Tejutepeque", label: "Tejutepeque" },
		{ value: "Victoria", label: "Victoria" },
	],
	"La Paz": [
		{ value: "Cuyultitán", label: "Cuyultitán" },
		{ value: "El Rosario", label: "El Rosario" },
		{ value: "Jerusalén", label: "Jerusalén" },
		{ value: "Mercedes La Ceiba", label: "Mercedes La Ceiba" },
		{ value: "Olocuilta", label: "Olocuilta" },
		{ value: "Paraíso de Osorio", label: "Paraíso de Osorio" },
		{ value: "San Antonio Masahuat", label: "San Antonio Masahuat" },
		{ value: "San Emigdio", label: "San Emigdio" },
		{ value: "San Francisco Chinameca", label: "San Francisco Chinameca" },
		{ value: "San Juan Nonualco", label: "San Juan Nonualco" },
		{ value: "San Juan Talpa", label: "San Juan Talpa" },
		{ value: "San Juan Tepezontes", label: "San Juan Tepezontes" },
		{ value: "San Luis Talpa", label: "San Luis Talpa" },
		{ value: "San Miguel Tepezontes", label: "San Miguel Tepezontes" },
		{ value: "San Pedro Masahuat", label: "San Pedro Masahuat" },
		{ value: "San Pedro Nonualco", label: "San Pedro Nonualco" },
		{ value: "San Rafael Obrajuelo", label: "San Rafael Obrajuelo" },
		{ value: "Santa María Ostuma", label: "Santa María Ostuma" },
		{ value: "Santiago Nonualco", label: "Santiago Nonualco" },
		{ value: "Tapalhuaca", label: "Tapalhuaca" },
		{ value: "Zacatecoluca", label: "Zacatecoluca" },
	],
	Usulután: [
		{ value: "Alegría", label: "Alegría" },
		{ value: "Berlín", label: "Berlín" },
		{ value: "California", label: "California" },
		{ value: "Concepción Batres", label: "Concepción Batres" },
		{ value: "El Triunfo", label: "El Triunfo" },
		{ value: "Ereguayquín", label: "Ereguayquín" },
		{ value: "Estanzuelas", label: "Estanzuelas" },
		{ value: "Jiquilisco", label: "Jiquilisco" },
		{ value: "Jucuapa", label: "Jucuapa" },
		{ value: "Jucuarán", label: "Jucuarán" },
		{ value: "Mercedes Umaña", label: "Mercedes Umaña" },
		{ value: "Nueva Granada", label: "Nueva Granada" },
		{ value: "Ozatlán", label: "Ozatlán" },
		{ value: "Puerto El Triunfo", label: "Puerto El Triunfo" },
		{ value: "San Agustín", label: "San Agustín" },
		{ value: "San Buenaventura", label: "San Buenaventura" },
		{ value: "San Dionisio", label: "San Dionisio" },
		{ value: "San Francisco Javier", label: "San Francisco Javier" },
		{ value: "Santa Elena", label: "Santa Elena" },
		{ value: "Santa María", label: "Santa María" },
		{ value: "Santiago de María", label: "Santiago de María" },
		{ value: "Tecapán", label: "Tecapán" },
		{ value: "Usulután", label: "Usulután" },
	],
	"San Miguel": [
		{ value: "Carolina", label: "Carolina" },
		{ value: "Chapeltique", label: "Chapeltique" },
		{ value: "Chinameca", label: "Chinameca" },
		{ value: "Chirilagua", label: "Chirilagua" },
		{ value: "Ciudad Barrios", label: "Ciudad Barrios" },
		{ value: "Comacarán", label: "Comacarán" },
		{ value: "El Tránsito", label: "El Tránsito" },
		{ value: "Lolotique", label: "Lolotique" },
		{ value: "Moncagua", label: "Moncagua" },
		{ value: "Nueva Guadalupe", label: "Nueva Guadalupe" },
		{ value: "Nuevo Edén de San Juan", label: "Nuevo Edén de San Juan" },
		{ value: "Quelepa", label: "Quelepa" },
		{ value: "San Antonio del Mosco", label: "San Antonio del Mosco" },
		{ value: "San Gerardo", label: "San Gerardo" },
		{ value: "San Jorge", label: "San Jorge" },
		{ value: "San Luis de la Reina", label: "San Luis de la Reina" },
		{ value: "San Miguel", label: "San Miguel" },
		{ value: "San Rafael Oriente", label: "San Rafael Oriente" },
		{ value: "Sesori", label: "Sesori" },
		{ value: "Uluazapa", label: "Uluazapa" },
	],
	Morazán: [
		{ value: "Arambala", label: "Arambala" },
		{ value: "Cacaopera", label: "Cacaopera" },
		{ value: "Chilanga", label: "Chilanga" },
		{ value: "Corinto", label: "Corinto" },
		{ value: "Delicias de Concepción", label: "Delicias de Concepción" },
		{ value: "El Divisadero", label: "El Divisadero" },
		{ value: "El Rosario", label: "El Rosario" },
		{ value: "Gualococti", label: "Gualococti" },
		{ value: "Guatajiagua", label: "Guatajiagua" },
		{ value: "Joateca", label: "Joateca" },
		{ value: "Jocoaitique", label: "Jocoaitique" },
		{ value: "Jocoro", label: "Jocoro" },
		{ value: "Lolotiquillo", label: "Lolotiquillo" },
		{ value: "Meanguera", label: "Meanguera" },
		{ value: "Osicala", label: "Osicala" },
		{ value: "Perquín", label: "Perquín" },
		{ value: "San Carlos", label: "San Carlos" },
		{ value: "San Fernando", label: "San Fernando" },
		{ value: "San Francisco Gotera", label: "San Francisco Gotera" },
		{ value: "San Isidro", label: "San Isidro" },
		{ value: "San Simón", label: "San Simón" },
		{ value: "Sensembra", label: "Sensembra" },
		{ value: "Sociedad", label: "Sociedad" },
		{ value: "Torola", label: "Torola" },
		{ value: "Yamabal", label: "Yamabal" },
		{ value: "Yoloaiquín", label: "Yoloaiquín" },
	],
	"La Unión": [
		{ value: "Anamorós", label: "Anamorós" },
		{ value: "Bolívar", label: "Bolívar" },
		{ value: "Concepción de Oriente", label: "Concepción de Oriente" },
		{ value: "Conchagua", label: "Conchagua" },
		{ value: "El Carmen", label: "El Carmen" },
		{ value: "El Sauce", label: "El Sauce" },
		{ value: "Intipucá", label: "Intipucá" },
		{ value: "La Unión", label: "La Unión" },
		{ value: "Lislique", label: "Lislique" },
		{ value: "Meanguera del Golfo", label: "Meanguera del Golfo" },
		{ value: "Nueva Esparta", label: "Nueva Esparta" },
		{ value: "Pasaquina", label: "Pasaquina" },
		{ value: "Polorós", label: "Polorós" },
		{ value: "San Alejo", label: "San Alejo" },
		{ value: "San José", label: "San José" },
		{ value: "Santa Rosa de Lima", label: "Santa Rosa de Lima" },
		{ value: "Yayantique", label: "Yayantique" },
		{ value: "Yucuaiquín", label: "Yucuaiquín" },
	],
};
